# Generated by Django 4.0.4 on 2022-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
