# Generated by Django 4.0.4 on 2022-06-15 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='heart_rate',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
