# Generated by Django 4.0.4 on 2022-06-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_patients_heart_rate_alter_patients_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='heart_rate',
        ),
    ]
