# Generated by Django 4.0.4 on 2022-06-16 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_remove_patients_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='heart_rate',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
