# Generated by Django 4.0.4 on 2022-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_patients_heart_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='heart_rate',
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(),
        ),
    ]
